# Computação vetorizada

## Objetivos

- Compreender as capacidades da computação vetorizada;
- Associar conceitos abstratos de Matemática a estruturas computacionais; 
- Saber estruturar dados em arrays multidimensionais;

## Introdução

- Computação científica, problemas de alta complexidade e recursos computacionais. 
- Resolução eficiente de problemas na ciência de dados
- Computação vetorizada (arrays x listas)

## O pacote *numpy* 

- Biblioteca padrão em Python para trabalhar com *arrays* multidimensionais e computação vetorizada. 
- Superpoderes às listas
> A grande regra: _vetorize seus cálculos numéricos o máximo possível!_

In [1]:
import numpy as np

## Motivação

Este exemplo compara a eficiência de operações feitas com listas comuns e com *numpy*.

In [2]:
# 1 µs = 1/1e6 segundo
# 1 ns = 1/1e9 segundo

L = range(500)
%timeit -n 10 [i**2 for i in L] # executa o laço 10 vezes

a = np.arange(500)
%timeit -n 10 a**2 # eleva ao quadrado diretamente 10 vezes

142 µs ± 18.5 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
956 ns ± 573 ns per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Criação de arrays unidimensionais (1D)

In [3]:
a = [1,2,3]
np.array(a) # a partir de lista

array([1, 2, 3])

In [4]:
np.array([1,2,3]) # diretamente

array([1, 2, 3])

In [5]:
np.array([2]*5)

array([2, 2, 2, 2, 2])

## Criação de arrays bidimensionais (2D)

In [6]:
A = [ [1,2], [0,2] ] # lista de listas
np.array(A) # matrix 2 x 2

array([[1, 2],
       [0, 2]])

In [7]:
np.array([ [1,2], [0,2] ]) # diretamente

array([[1, 2],
       [0, 2]])

In [8]:
A2 = [[1,2,3],[4,3,2]] # cada lista é uma linha da matriz
np.array(A2) # matriz 2 x 3 

array([[1, 2, 3],
       [4, 3, 2]])

In [9]:
np.array([1,1],[0,1]) # parênteses externos são obrigatórios! 

TypeError: Field elements must be 2- or 3-tuples, got '0'

### Dimensão, formato e comprimento

In [11]:
x = np.array(a)
np.ndim(x) # aplica a função ndim

1

In [12]:
x.ndim # como método

1

In [13]:
np.shape(x) # formato

(3,)

In [14]:
x.shape # sem parênteses

(3,)

In [15]:
len(x) # comprimento

3

In [16]:
X = np.array(A)
np.ndim(X) # array bidimensional

2

In [17]:
np.shape(X) 

(2, 2)

In [18]:
len(X) # apenas um comprimento. Qual?

2

In [19]:
X2 = np.array(A2)
len(X2) # apenas da primeira dimensão. LINHAS

2

In [20]:
X2.shape

(2, 3)

## Funções para criação de arrays

### `arange`

**Exemplo:** crie um array de números ímpares positivos menores do que 36.

In [21]:
np.arange(1,36,2) # start,stop,step

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35])

**Exemplo:** crie um array de números pares positivos menores ou iguais a 62.

In [22]:
np.arange(0,63,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62])

**Exemplo:** calcule o valor de $f(x) = x^3 + 2x$ para $x$ elementos dos arrays anteriores.

In [23]:
imp, par = np.arange(1,36,2), np.arange(0,63,2)
f = lambda x: x**3 + 2
fi, fp = f(imp), f(par)
print(fi)
print(fp)

[    3    29   127   345   731  1333  2199  3377  4915  6861  9263 12169
 15627 19685 24391 29793 35939 42877]
[     2     10     66    218    514   1002   1730   2746   4098   5834
   8002  10650  13826  17578  21954  27002  32770  39306  46658  54874
  64002  74090  85186  97338 110594 125002 140610 157466 175618 195114
 216002 238330]


### `linspace`

**Exemplo:** crie um array igualmente espaçado de elementos em [0,1] com 11 elementos.

In [24]:
np.linspace(0,1,num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [25]:
np.linspace(0,1,11) # 'num' pode ser omitido

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [26]:
x = np.linspace(0,1,10,endpoint=False) # exclui último
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [27]:
y = np.arange(0,1,0.1) # equivalente
y

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [28]:
x == y # comparação é elemento a elemento

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [29]:
x == -y # apenas 0 é True

array([ True, False, False, False, False, False, False, False, False,
       False])

In [30]:
x[1:] == y[1:]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

### `all` e `any`

In [31]:
np.all( x == y ) # verifica se todos são 'True'

True

In [32]:
np.any( x == -y ) # verifica se pelo menos um é 'True'

True

### `random`

**Exemplo**: crie um *array* 1D com 5 números aleatórios entre [0,1].

In [33]:
r = np.random.rand(5)
r

array([0.75244621, 0.26501672, 0.14144404, 0.95259126, 0.97398165])

**Exemplo**: crie um *array* 1D com 50 números inteiros aleatórios entre [0,7].

In [34]:
r2 = np.random.randint(0,7+1,50) # menor, maior é 8 (exclusive), tamanho
r2

array([3, 0, 5, 7, 6, 1, 7, 5, 3, 2, 5, 6, 2, 2, 1, 5, 0, 5, 0, 3, 0, 3,
       0, 7, 6, 3, 3, 3, 1, 4, 2, 2, 1, 2, 3, 6, 4, 1, 2, 1, 2, 7, 7, 2,
       2, 7, 0, 7, 2, 2])

**Exemplo**: crie uma matriz m x n com números inteiros aleatórios entre inteiros [l,h].

In [35]:
def gera_matriz(m,n,l,h):
    return np.random.randint(l,h,(m,n)) # tupla (m,n)

In [36]:
gera_matriz(2,2,0,4)

array([[0, 1],
       [0, 0]])

In [37]:
gera_matriz(3,2,0,4)

array([[1, 0],
       [0, 2],
       [0, 3]])

In [38]:
gera_matriz(4,4,-2,7)

array([[-1,  3,  3,  1],
       [ 1,  0,  4,  3],
       [ 4,  5,  0,  1],
       [ 6,  1,  6,  3]])

### `ones`

Criando arrays unitários.

In [39]:
np.ones(4) 

array([1., 1., 1., 1.])

In [40]:
np.ones((3,2)) # tupla necessária para linhas e colunas

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### `eye`

Criando arrays 2D identidade. 1 na diagonal e 0 nas demais.

In [41]:
np.eye(3) # matriz identidade 3 x 3 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### `zeros`

Arrays nulos.

In [42]:
np.zeros(3)

array([0., 0., 0.])

In [43]:
np.zeros((2,4)) # 2 x 4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### `full`

Arrays de valor constante.

In [44]:
np.full(3,0) # 1 x 3 com constante 0

array([0, 0, 0])

In [45]:
np.full(shape=(3,),fill_value=0)

array([0, 0, 0])

In [46]:
F1 = np.full(shape=(2,2),fill_value=1) # 2 x 2 com 1
F1

array([[1, 1],
       [1, 1]])

In [47]:
F1 == np.ones(2) # mesmo resultado que ones

array([[ True,  True],
       [ True,  True]])

Outras maneiras:

In [48]:
F2 = 3*np.ones((4,4))
F2

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

## Especificando tipos de dados 

Observe o seguinte exemplo:

In [49]:
F2

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [50]:
F3 = np.full((4,4),3)
F3

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [51]:
F2 == F3 # valores iguais

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [52]:
F2.dtype == F3.dtype # tipos diferentes

False

In [53]:
F2.dtype

dtype('float64')

In [54]:
F3.dtype

dtype('int64')

Especificamos o tipo de dados com `dtype`.

In [55]:
np.ones((4,2),dtype=bool) # matriz de booleanos

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [56]:
np.ones((4,2),dtype=str) # matriz de strings; 'U1' diz que há no máximo 1 caracter

array([['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [57]:
S = np.array(['dias','mes','ano'])
S.dtype # 4 é o no. máximo de caracteres nas strings

dtype('<U4')

## Indexação e fatiamento

Funcionam de maneira similar ao uso com listas.

In [58]:
I = np.linspace(0,20,11)
I

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [59]:
I[3],I[2:4],I[5:8],I[-4:-1]

(6.0, array([4., 6.]), array([10., 12., 14.]), array([14., 16., 18.]))

In [60]:
I[::-1] # invertendo o array

array([20., 18., 16., 14., 12., 10.,  8.,  6.,  4.,  2.,  0.])

In [61]:
I2 = np.array([I,2*I,3*I,4*I])
I2

array([[ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.],
       [ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40.],
       [ 0.,  6., 12., 18., 24., 30., 36., 42., 48., 54., 60.],
       [ 0.,  8., 16., 24., 32., 40., 48., 56., 64., 72., 80.]])

Em arrays bidimensionais, a indexação é feita por meio de uma tupla. Porém, a explicitação dos parênteses é desnecessária.

In [62]:
I2[(2,3)] # 3a. linha; 4a. coluna

18.0

In [63]:
I2[2,3]

18.0

In [64]:
I2[0,:] # 1a. linha

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [65]:
I2[1,:] # 2a. linha

array([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40.])

In [66]:
I2[-1,:] # última linha

array([ 0.,  8., 16., 24., 32., 40., 48., 56., 64., 72., 80.])

In [67]:
I2[:,0] # 1a. coluna

array([0., 0., 0., 0.])

In [68]:
I2[:,1] # 2a. coluna

array([2., 4., 6., 8.])

In [69]:
I2[:,8] # 9a. coluna

array([16., 32., 48., 64.])

In [70]:
I2[:,2:4] # 3a. - 4a. coluna

array([[ 4.,  6.],
       [ 8., 12.],
       [12., 18.],
       [16., 24.]])

In [71]:
I2[1:3,6:10] # submatriz: linhas 2 - 3; 7-10

array([[24., 28., 32., 36.],
       [36., 42., 48., 54.]])

### Alteração de valores

Os arrays são mutáveis por indexação.

In [72]:
A3 = np.random.rand(4,4)
A3

array([[0.57972205, 0.46392454, 0.33007748, 0.69741516],
       [0.70287421, 0.67064379, 0.83157008, 0.63693705],
       [0.41980667, 0.90585255, 0.83123388, 0.75172506],
       [0.80275361, 0.79796257, 0.91765365, 0.41429831]])

In [73]:
A3[0:4,0] = -1
A3

array([[-1.        ,  0.46392454,  0.33007748,  0.69741516],
       [-1.        ,  0.67064379,  0.83157008,  0.63693705],
       [-1.        ,  0.90585255,  0.83123388,  0.75172506],
       [-1.        ,  0.79796257,  0.91765365,  0.41429831]])

In [74]:
A3[:,-1] = -1
A3

array([[-1.        ,  0.46392454,  0.33007748, -1.        ],
       [-1.        ,  0.67064379,  0.83157008, -1.        ],
       [-1.        ,  0.90585255,  0.83123388, -1.        ],
       [-1.        ,  0.79796257,  0.91765365, -1.        ]])

In [75]:
A3[1:3,1:3] = 0
A3

array([[-1.        ,  0.46392454,  0.33007748, -1.        ],
       [-1.        ,  0.        ,  0.        , -1.        ],
       [-1.        ,  0.        ,  0.        , -1.        ],
       [-1.        ,  0.79796257,  0.91765365, -1.        ]])

Podemos alterar valores com arrays.

In [76]:
A3[1,:] = -2*np.ones(4)
A3

array([[-1.        ,  0.46392454,  0.33007748, -1.        ],
       [-2.        , -2.        , -2.        , -2.        ],
       [-1.        ,  0.        ,  0.        , -1.        ],
       [-1.        ,  0.79796257,  0.91765365, -1.        ]])

A indexação pode usar um comprimento de passo (*step*).

In [77]:
A3[0:4:3,1:3] = np.full((1,2),8) # na indexação esquerda, 1a. linha : 4a. linha : step de 3
A3

array([[-1.,  8.,  8., -1.],
       [-2., -2., -2., -2.],
       [-1.,  0.,  0., -1.],
       [-1.,  8.,  8., -1.]])

### `newaxis`

`newaxis` é uma instância do `numpy` que permite aumentar de 1 a dimensão de um array existente. 

**Exemplo:** como inserir a diagonal de uma matriz em uma segunda matriz como uma coluna adicional?

Criamos duas matrizes aleatórias.

In [78]:
# matriz 4 x 4 de inteiros aleatórios entre 0 e 9
B1 = np.random.randint(0,10,(4,4)) 
B1

array([[5, 1, 4, 4],
       [2, 1, 2, 7],
       [3, 6, 1, 4],
       [9, 7, 1, 9]])

In [79]:
# matriz 4 x 4 de inteiros aleatórios entre -10 e 9
B2 = np.random.randint(-10,10,(4,4)) 
B2

array([[ 3,  8,  6, -4],
       [ 6,  1,  7,  8],
       [ 1, -8, -1,  7],
       [-1, -8, -2,  4]])

Extraímos a diagonal da primeira.

In [80]:
# diagonal de B1
db1 = np.diag(B1)
db1

array([5, 1, 1, 9])

Notemos agora que as dimensões são diferentes.

In [81]:
print(B2.ndim)
print(db1.ndim)

2
1


Para podermos aglutinar a diagonal como uma nova coluna na primeira matriz, primeiro temos que transformar o array unidimensional para uma matriz.  

In [82]:
db1 = db1[:,np.newaxis]
print(db1.ndim) # agora o array é bidimensional
db1 

2


array([[5],
       [1],
       [1],
       [9]])

`newaxis` é um "eixo imaginário" incluído *inplace*, mas que altera dinamicamente o array. No caso acima, o array tornou-se em uma coluna.

Agora, podemos "colar" um array 2D com outro por uma concatenação. 

### `concatenate`

`concatenate` é usado para concatenar *arrays*. A concatenação requer uma tupla contendo os *arrays* a concatenar e o eixo de referência.

In [83]:
B3 = np.concatenate((B2,db1), axis=1) 
B3

array([[ 3,  8,  6, -4,  5],
       [ 6,  1,  7,  8,  1],
       [ 1, -8, -1,  7,  1],
       [-1, -8, -2,  4,  9]])

No caso acima, `axis=1` indica que a concatenação é ao longo da coluna. Dessa forma, inserimos a segunda diagonal como uma coluna adicional na segunda matriz. Claramente, isto só é possível porque ambas as matrizes eram de mesmo formato.

#### `axis`

Nos arrays multidimensionais do Python, `axis` é usado para indicar a "direção" dos dados. Em arrays bidimensionais, `axis=0` refere-se à direção de cima para baixo (ao longo das linhas), ao passo que `axis=1` refere-se à direção da esquerda para a direita (ao longo das colunas). 

**Obs.:** note que a palavra `axis` ("eixo") deve ser usada, e não "axes" ("eixos").

Para aglutinar uma linha na matriz anterior, fazemos uma concatenação em linha.

In [84]:
# array de zeros com mesmo número de colunas de B3
db2 = np.zeros(np.shape(B3)[1]) 
db2

array([0., 0., 0., 0., 0.])

In [85]:
db2 = db2[np.newaxis,:] # cria o "eixo imaginário" na direção 0

In [86]:
B4 = np.concatenate((B3,db2),axis=0) # concatena ao longo das linhas
B4

array([[ 3.,  8.,  6., -4.,  5.],
       [ 6.,  1.,  7.,  8.,  1.],
       [ 1., -8., -1.,  7.,  1.],
       [-1., -8., -2.,  4.,  9.],
       [ 0.,  0.,  0.,  0.,  0.]])

## Indexação avançada

Podemos usar máscaras como artifícios para indexação avançada.

In [87]:
IA1 = np.arange(-10,11)
IA1

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9,  10])

Vamos criar um *array* aleatório de True e False no mesmo formato que o *array* anterior.

In [88]:
mask1 = np.random.randint(0,2,np.shape(IA1),dtype=bool) 
mask1 

array([False,  True, False,  True,  True, False,  True,  True,  True,
       False,  True, False, False,  True,  True, False, False, False,
       False, False, False])

Esta *máscara booleana* pode ser aplicada no array para extrair apenas os elementos cujos índices são marcados como `True` pela máscara.

In [89]:
IA1[mask1]

array([-9, -7, -6, -4, -3, -2,  0,  3,  4])

Há maneiras mais diretas aplicáveis a filtragens. Para extrair os valores negativos do array:

In [90]:
IA1 < 0 # máscara booleana

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False])

In [91]:
IA1[IA1 < 0] 

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])

Para extrair os valores positivos do array:

In [92]:
IA1[IA1 > 0] # máscara booleana para positivos

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Para extrair os valores no intervalo $]-2,5[$, fazemos:

In [93]:
IA1[(IA1 > -2) & (IA1 < 5)] # & é o operador booleano 'elemento a elemento'

array([-1,  0,  1,  2,  3,  4])

Para extrair pares e ímpares, poderíamos fazer:

In [94]:
pares, impares = IA1[IA1 % 2 == 0] , IA1[IA1 % 2 == 1] 
pares,impares 

(array([-10,  -8,  -6,  -4,  -2,   0,   2,   4,   6,   8,  10]),
 array([-9, -7, -5, -3, -1,  1,  3,  5,  7,  9]))

Podemos usar listas como máscaras:

In [95]:
alguns = pares[[0,2,3,5]] # acessa 1o., 3o. 4o. e 6o. elemento de 'pares'

In [96]:
impares[alguns] # estude este caso

array([-9, -1,  3, -9])

No caso acima, por exemplo, -10 é uma indexação reversa que excede o compriemento do array à esquerda. Portanto, ele retorna o primeiro elemento do array, que é -9. O índice -6 acessa o sexto elemento a partir da direita, que é -1. O índice -4 acessa o quarto elemento a partir da direita. Por fim, o índice 0 acessa o primeiro elemento que é -9. 

## Operações elemento a elemento

As operações aritméticas e de cálculo são feitas elemento a elemento nos *arrays*. Já mostramos alguns exemplos acima, mas vamos tornar isto mais claro aqui.

In [97]:
a = np.array([1,2,3]) 
b = np.array([4,5,6])

In [98]:
# operações elemento a elemento
print(a + b) 
print(a - b) 
print(a * b) 
print(a / b)
print(a ** b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [99]:
2*a + 4*b - 6*b**2 + 1.1/2*a

array([ -77.45, -124.9 , -184.35])

## Funções matemáticas

O `numpy` possui a maioria dass funções disponíveis no módulo `math` e outras mais. As funções são diretamente aplicáveis aos *arrays*. Lembre-se que para fazer o mesmo usando em listas, tínhamos de construir meios de iterar sobre elas e aplicar a função a cada elemento por vez. Isto não é mais necessário com o `numpy`. Eis a beleza da computação vetorizada!

Vejamos uma série de exemplos.

In [100]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [102]:
np.cos(x) + 2*np.sqrt(x)

array([1.        , 2.54030231, 2.41228029, 2.47410912, 3.34635638,
       4.75579814, 5.85914977, 6.04540488, 5.51135422, 5.08886974])

In [103]:
y = np.sin(2*x)
z = np.exp(x + y)
y - z

array([-1.00000000e+00, -5.83904850e+00, -4.22348298e+00, -1.54686133e+01,
       -1.45852799e+02, -8.66844526e+01, -2.36441078e+02, -2.95209938e+03,
       -2.23551181e+03, -3.82459986e+03])

## *Broadcasting*

*Broadcasting* é a capacidade que o *numpy* oferece para realizarmos operações em arrays com diferentes dimensões.

### Regras do *broadcasting* 

1. Se dois *arrays* tiverem dimensões diferentes, o formato do array com menor dimensão é preenchido por 1 do lado esquerdo.
2. Se o formato dos *arrays* não for igual em dimensão alguma, o array com tamanho igual a 1 é esticado nesta direção para ficar no mesmo tamanho correspondente do outro array.
3. Se em qualquer direção os tamanhos dos *arrays* forem diferentes e nenhum deles for igual a 1, então um erro é retornado.

#### Exemplo da Regra 1

In [104]:
A = np.array([[1, 2, 3],[4, 5, 6]]) # array 2D
b = np.array([10, 20, 30]) # array 1D
print(A.shape)
print(b.shape)

(2, 3)
(3,)


In [105]:
A + b

array([[11, 22, 33],
       [14, 25, 36]])

A soma pode ser realizada mesmo assim. O que ocorreu? Cada linha de `A` foi somada à única linha de `b`. O *broadcasting* amplia o array de menor dimensão automaticamente da seguinte forma:

Pela regra 1, o *array* `b` tem dimensão menor. Então, ele é preenchido de modo que:

```python
A.shape -> (2, 3)
b.shape -> (1, 3)
```

Pela regra 2, a primeira dimensão de `A` é 2 e a de `b` é 1. Então, a dimensão de `b` é "esticada", de modo que:

```python
A.shape -> (2, 3)
b.shape -> (2, 3)
```

A mesma operação poderia ter sido feita com:

In [106]:
A + np.array([b,b])

array([[11, 22, 33],
       [14, 25, 36]])

#### Exemplo da Regra 2

In [107]:
A = np.arange(3).reshape((3, 1))
b = np.arange(3) 
print(A.shape)
print(b.shape)

(3, 1)
(3,)


In [108]:
A + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Neste caso, ambos os arrays sofrem *broadcasting*. Ele ocorre da seguinte forma.

Como 

```python 
A.shape = (3, 1)
b.shape = (3,)
```
a regra 1 diz que `b` deve ser preenchido de modo que

```python
A.shape -> (3, 1)
b.shape -> (1, 3)
```
e, pela regra 2, cada uma das dimensões 1 deve ser alterada de modo que:

```python
A.shape -> (3, 3)
b.shape -> (3, 3)
```

Assim, o *broadcasting* é permitido.

#### Exemplo da Regra 3

In [109]:
A = np.ones((3, 2))
b = np.arange(3)
print(A.shape)
print(b.shape)

(3, 2)
(3,)


In [110]:
A + b

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

Neste exemplo, o *broadcasting* não é permitido. O caso é levemente diferente do primeiro exemplo em que `A` é transposta.

Temos que 

```python 
M.shape = (3, 2)
a.shape = (3,)
```

Pela regra 1, devemos ter

```python
M.shape -> (3, 2)
a.shape -> (1, 3)
```

e, pela regra 2, a primeira dimensão deve ser esticada para combinar-se com a de `A` enquanto a segunda não é alterada por não ser 1.

```python
M.shape -> (3, 2)
a.shape -> (3, 3)
```
Porém, o formato final de ambos não se combina. Sendo incompatíveis, o *broadcasting* falha.